auth0:
  baseURL:      'https://dcl-test.auth0.com'

logLevel: 'DEBUG' # Set LOG_LEVEL env variable to overwrite this value

server:
    port: 9091 # Listening port
    url: "http://localhost:9091/" # Base service url without the last /

jwt:
  duration: 60  # Duration in seconds of the json web token