version: "3.7"
services:
  gameauth:
    image: decentraland/game-authentication:78d0b4c17c661bc2cb5d68b1c224105b9b2933df
    command: build/identity --host=0.0.0.0
    ports:
      - "9001:9001"

  coordinator:
    image: golang:1.12.0
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: ./bin/wait-for-it gameauth:9001 -- go run cmd/comms/coordinator/main.go --host=0.0.0.0 --authEnabled=false
    ports:
      - "9000:9000"
      - "9080:9080"
    depends_on:
      - gameauth
    environment:
     - DD_AGENT_HOST

  worldcomm:
    image: golang:1.12.0
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: ./bin/wait-for-it --coordinator:9000 -- ./bin/wait-for-it db:5432 -- go run cmd/comms/server/main.go --statsDBHost=db --statsDBPort=5432 --statsDBName=statsdb --statsDBUser=postgres --statsDBPassword=password --authEnabled=false
    tty: true
    ports:
      - "9081:9081"
    depends_on:
      - gameauth
      - coordinator
    environment:
     - DD_AGENT_HOST

  datadog:
    image: datadog/agent:latest
    links:
     - worldcomm
    environment:
     - DD_API_KEY
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
     - DD_LOG_LEVEL=error
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./bin/compose-init-db.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./internal/commserver/db.sql:/docker-entrypoint-initdb.d/sql/init_stats.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
