host:       '0.0.0.0'   # Set -host flag to overwrite this value
port:       8081          # Set -port flag to overwrite this value
connStr:    ""            # Set -connStr flag to overwrite this value
schemaDir:  "pkg/profile" # Set -schemaDir flag to overwrite this value
auth:
  mode:       "third-party" # Set auth-mode flag to overwrite this value
  requestTTL: 60            # Set auth-ttl flag to overwrite this value
