version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build
          command: make build

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Run profile test
          command: make profileci PROFILE_TEST_DB_CONN_STR="postgres://testuser@localhost/testdb?sslmode=disable"

      - run:
          name: Run identity test
          command: make identityci

  build:
    docker:
      - image: circleci/golang:1.12
        environment: &ENVIRONMENT
          DOCKER_IMAGE_NAME: decentraland/world

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build
          command: make build

      - setup_remote_docker: { docker_layer_caching: true }

      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 .

      - run:
          name: Log in DockerHub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

      - run:
          name: Push image
          command: |
            if echo "$CIRCLE_BRANCH" | grep "^master$"; then
              docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1" "$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH"
              docker push "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1"
            elif echo "$CIRCLE_BRANCH" | grep "^dev$"; then
              docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1" "$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH"
              docker push "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1"
            elif echo "$CIRCLE_TAG" | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
              docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1" "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"
              docker push "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"
            else
              echo "Not a release, skipping push"
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            branches:
                only:
                - master
                - dev
