identityURL: "http://gameauth:9001/api/v1"
coordinatorURL: "ws://coordinator:9000"

auth0:
  domain:   'dcl-test.auth0.com'

coordinator:
    host: 'localhost'
    port: 9000
    healthCheckPort: 9080
    logLevel: 'debug'
    authTTL: 60
    serverSecret: "123456"
    metrics:
        enabled: true
        traceName: 'coordinator-local'

commserver:
    logLevel: 'debug'
    authTTL: 60
    serverSecret: "123456"
    metrics:
        enabled: true
        traceName: 'commserver-local'

gameauth:
    publicURL: "http://gameauth:9001"
    host: 'localhost'
    port: 9001
    logLevel: 'debug'
    jwtDuration: 60
    clientsDataPath: 'config/identity/enabledClients.json'
    privateKeyPath: "config/identity/devKeys/demoPrivate.key"
    metrics:
        enabled: false
        traceName: 'identityService'

cli:
  auth0ClientID: lTUEMnFpYb0aiUKeIRPbh7pBxKM6sccx
  auth0Audience: decentraland.org
